version: '3.9'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
    volumes:
      - /home/entropay-scan/branding/icons/sprite.9aac2f78.svg:/app/public/icons/sprite.9aac2f78.svg:ro
      - /home/entropay-scan/branding/patch_frontend_branding.sh:/app/patch_frontend_branding.sh:ro
      - /home/entropay-scan/branding/entrypoint.sh:/app/entrypoint.sh:ro
    command: ["node", "server.js"]
